NAME_MAP = {
    'Arsenal': 'Arsenal',
    'Aston Villa': 'Aston Villa',
    'Bournemouth': 'Bournemouth',
    'Brentford': 'Brentford',
    'Brighton': 'Brighton & Hove Albion',
    'Burnley': 'Burnley',
    'Chelsea': 'Chelsea',
    'Crystal Palace': 'Crystal Palace',
    'Everton': 'Everton',
    'Fulham': 'Fulham',
    'Ipswich': 'Ipswich Town',
    'Leeds': 'Leeds United',
    'Leicester': 'Leicester City',
    'Liverpool': 'Liverpool',
    'Man City': 'Manchester City',
    'Man United': 'Manchester United',
    'Newcastle': 'Newcastle United',
    "Nott'm Forest": 'Nottingham Forest',
    'Southampton': 'Southampton',
    'Sunderland': 'Sunderland',
    'Tottenham': 'Tottenham Hotspur',
    'West Ham': 'West Ham United',
    'Wolves': 'Wolverhampton Wanderers',
    'AFC Wimbledon': 'Wimbledon',
    'Accrington': 'Accrington Stanley',
    'Barnet': 'Barnet',
    'Barnsley': 'Barnsley',
    'Barrow': 'Barrow',
    'Birmingham': 'Birmingham City',
    'Blackburn': 'Blackburn Rovers',
    'Blackpool': 'Blackpool',
    'Bolton': 'Bolton Wanderers',
    'Bradford': 'Bradford City',
    'Bristol City': 'Bristol City',
    'Bristol Rvs': 'Bristol Rovers',
    'Bromley': 'Bromley',
    'Burton': 'Burton Albion',
    'Cambridge': 'Cambridge United',
    'Cardiff': 'Cardiff City',
    'Carlisle': 'Carlisle United',
    'Charlton': 'Charlton Athletic',
    'Cheltenham': 'Cheltenham Town',
    'Chesterfield': 'Chesterfield',
    'Colchester': 'Colchester United',
    'Coventry': 'Coventry City',
    'Crawley Town': 'Crawley Town',
    'Crewe': 'Crewe Alexandra',
    'Derby': 'Derby County',
    'Doncaster': 'Doncaster Rovers',
    'Exeter': 'Exeter City',
    'Fleetwood Town': 'Fleetwood Town',
    'Forest Green': 'Forest Green Rovers',
    'Gillingham': 'Gillingham',
    'Grimsby': 'Grimsby Town',
    'Harrogate': 'Harrogate Town',
    'Hartlepool': 'Hartlepool United',
    'Huddersfield': 'Huddersfield Town',
    'Hull': 'Hull City',
    'Leyton Orient': 'Leyton Orient',
    'Lincoln': 'Lincoln City',
    'Luton': 'Luton Town',
    'Mansfield': 'Mansfield Town',
    'Middlesbrough': 'Middlesbrough',
    'Millwall': 'Millwall',
    'Milton Keynes Dons': 'Milton Keynes Dons',
    'Morecambe': 'Morecambe',
    'Newport County': 'Newport County',
    'Northampton': 'Northampton Town',
    'Norwich': 'Norwich City',
    'Notts County': 'Notts County',
    'Oldham': 'Oldham Athletic',
    'Oxford': 'Oxford United',
    'Peterboro': 'Peterborough United',
    'Plymouth': 'Plymouth Argyle',
    'Port Vale': 'Port Vale',
    'Portsmouth': 'Portsmouth',
    'Preston': 'Preston North End',
    'QPR': 'Queens Park Rangers',
    'Reading': 'Reading',
    'Rochdale': 'Rochdale',
    'Rotherham': 'Rotherham United',
    'Salford': 'Salford City',
    'Scunthorpe': 'Scunthorpe United',
    'Sheffield United': 'Sheffield United',
    'Sheffield Weds': 'Sheffield Wednesday',
    'Shrewsbury': 'Shrewsbury Town',
    'Stevenage': 'Stevenage',
    'Stockport': 'Stockport County',
    'Stoke': 'Stoke City',
    'Sutton': 'Sutton United',
    'Swansea': 'Swansea City',
    'Swindon': 'Swindon Town',
    'Tranmere': 'Tranmere Rovers',
    'Walsall': 'Walsall',
    'Watford': 'Watford',
    'West Brom': 'West Bromwich Albion',
    'Wigan': 'Wigan Athletic',
    'Wrexham': 'Wrexham',
    'Wycombe': 'Wycombe Wanderers',
    'York': 'York City',
}

def canonical_name(short_name):
    return NAME_MAP.get(short_name, short_name)
